name: configure
description: 워크플로우 공통 설정
runs:
  using: 'composite'
  steps:
    - name: Bot
      run: |
        git config user.name "FoodRhapsody"
        git config user.email "foodrhapsodie@gmail.com"
      shell: bash
    - name: "SINCE_FROM_REF 환경변수 설정"
      shell: bash
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          echo "SINCE_FROM_REF=$(git rev-parse HEAD~1)" >> $GITHUB_ENV
        elif [[ ${{ github.event_name }} == 'pull_request' ]]; then
          echo "SINCE_FROM_REF=$(git rev-parse origin/${{ github.base_ref }})" >> $GITHUB_ENV
        else
          echo "SINCE_FROM_REF=$(git rev-parse origin/main)" >> $GITHUB_ENV
        fi
