name: configure
description: Configure workflow common config
runs:
  using: 'composite'
  steps:
    - name: Bot
      run: |
        git config user.name "FoodRhapsody"
        git config user.email "foodrhapsodie@gmail.com"
      shell: bash
    - name: "set SINCE_FROM_REF environment"
      shell: bash
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          echo "SINCE_FROM_REF=$(git rev-parse HEAD~1)" >> $GITHUB_ENV
        elif [[ ${{ github.event_name }} == 'pull_request' ]]; then
          echo "SINCE_FROM_REF=$(git rev-parse origin/${{ github.base_ref }})" >> $GITHUB_ENV
        else
          echo "SINCE_FROM_REF=$(git rev-parse origin/main)" >> $GITHUB_ENV
        fi
