### GET /health
GET http://127.0.0.1:5000/health

### GET /version
GET http://127.0.0.1:5000/version

### POST /users
### Create new user
POST http://127.0.0.1:5000/users
Content-Type: application/json

{
  "email": "seokju.me@kakao.com",
  "oauth_provider": "kakao",
  "oauth_token": "..."
}

### GET /me
### Authorize me
GET http://127.0.0.1:5000/me
Authorization: Bearer ...

### POST /me/token
### Refresh my token
POST http://127.0.0.1:5000/me/token
Content-Type: application/json
Authorization: Bearer ...
