name = "challenges"
type = "javascript"
workers_dev = true
compatibility_date = "2022-01-16"
vars = { VERSION = "unknown" }
durable_objects.bindings = [
  { name = "CHALLENGES", class_name = "Challenges" }
]

[[migrations]]
tag = "v0" # Should be unique for each entry
new_classes = ["Challenges"] # Array of new classes

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[build.upload]
dir = "build/worker"
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type  = "CompiledWasm"

[env.test]
name = "challenges-test"
