name = "place"
type = "javascript"
workers_dev = true
compatibility_date = "2022-01-16"
vars = { VERSION = "unknown" }
kv_namespaces = [
  { binding = "PLACE", id = "6c7ab47d847e491bbf999cbe40311c34", preview_id = "c766100dcef8446dbf1be8a0af99f16a" }
]

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[build.upload]
dir = "build/worker"
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"

[env.test]
name = "place-test"
