### GET /health
GET {{ origin }}/health

### GET /version
GET {{ origin }}/version

### GET /challenges
GET {{ origin }}/challenges

### POST /challenges
POST {{ origin }}/challenges
Content-Type: application/json
Authorization: Bearer {{ access_token }}

{
  "name": "한우",
  "stamps": [
    {
      "id": "ribeye_roll",
      "title": "등심",
      "description": "육즙 가득",
      "img_url": ""
    }
  ]
}

### POST /users
POST {{ origin }}/users
Content-Type: application/json

{
  "email": "seokju.me@kakao.com",
  "oauth_provider": "kakao",
  "oauth_token": "..."
}

### GET /me
GET {{ origin }}/me
Authorization: Bearer {{ access_token }}

### POST /me/token
POST {{ origin }}/me/token
Authorization: Bearer {{ access_token }}

### POST /place/search
POST {{ origin }}/place/search?query=키친마이야르

### GET /foodnotes
GET {{ origin }}/foodnotes
Authorization: Bearer {{ access_token }}

### POST /foodnotes
POST {{ origin }}/foodnotes
Content-Type: application/json
Authorization: Bearer {{ access_token }}

{
  "stamp_id": "ribeye_roll",
  "author_id": "9VXFDl46hEG6PzFpiOpdP",
  "text": "와! 정말 맛있어요.",
  "place": {
    "id": "234127678",
    "place_name": "키친마이야르",
    "category_name": "음식점 > 양식",
    "category_group_code": "FD6",
    "category_group_name": "음식점",
    "phone": "02-511-7002",
    "address_name": "서울 강남구 신사동 644-6",
    "road_address_name": "서울 강남구 언주로170길 22",
    "x": "127.035423195622",
    "y": "37.5266092359544",
    "place_url": "http://place.map.kakao.com/234127678",
    "distance": ""
  },
  "img_urls": [],
  "is_public": false
}
