### GET /health
GET {{ origin }}/health

### GET /version
GET {{ origin }}/version

### GET /challenges
GET {{ origin }}/challenges

### POST /challenges
POST {{ origin }}/challenges
Content-Type: application/json
Authorization: Bearer ...

{
  "name": "한우",
  "stamps": [
    {
      "id": "ribeye_roll",
      "title": "등심",
      "description": "육즙 가득",
      "img_url": ""
    }
  ]
}

### POST /users
POST {{ origin }}/users
Content-Type: application/json

{
  "email": "seokju.me@kakao.com",
  "oauth_provider": "kakao",
  "oauth_token": "..."
}

### GET /me
GET {{ origin }}/me
Authorization: Bearer ...

### POST /me/token
POST {{ origin }}/me/token
Authorization: Bearer ...

### POST /place/search
POST {{ origin }}/place/search?query=키친마이야르
